# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boxpile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setStyleSheet("color: rgb(246, 246, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1081, 721))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.sideBarLayout = QtWidgets.QVBoxLayout()
        self.sideBarLayout.setSpacing(0)
        self.sideBarLayout.setObjectName("sideBarLayout")
        self.banner = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.banner.setFont(font)
        self.banner.setStyleSheet("color: rgb(254, 140, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"padding: 50px;\n"
"padding-left: 40px;\n"
"text-align: left;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/logoTR_orange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.banner.setIcon(icon)
        self.banner.setIconSize(QtCore.QSize(45, 45))
        self.banner.setObjectName("banner")
        self.sideBarLayout.addWidget(self.banner)
        self.btnCalendario = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalendario.setFont(font)
        self.btnCalendario.setStyleSheet("QPushButton {\n"
"    padding: 20px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.btnCalendario.setObjectName("btnCalendario")
        self.sideBarLayout.addWidget(self.btnCalendario)
        self.btnSeguimiento = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSeguimiento.setFont(font)
        self.btnSeguimiento.setStyleSheet("QPushButton {\n"
"    padding: 20px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.btnSeguimiento.setObjectName("btnSeguimiento")
        self.sideBarLayout.addWidget(self.btnSeguimiento)
        self.btnBusqueda = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnBusqueda.setFont(font)
        self.btnBusqueda.setStyleSheet("QPushButton {\n"
"    padding: 20px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.btnBusqueda.setObjectName("btnBusqueda")
        self.sideBarLayout.addWidget(self.btnBusqueda)
        self.sideBarFill = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.sideBarFill.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.sideBarFill.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBarFill.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBarFill.setObjectName("sideBarFill")
        self.sideBarLayout.addWidget(self.sideBarFill)
        self.btnUser = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        self.btnUser.setFont(font)
        self.btnUser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(8, 21, 63);\n"
"padding: 20px;\n"
"padding-left: 40px;\n"
"text-align: left")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/logoTR_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUser.setIcon(icon1)
        self.btnUser.setIconSize(QtCore.QSize(45, 45))
        self.btnUser.setObjectName("btnUser")
        self.sideBarLayout.addWidget(self.btnUser)
        self.mainLayout.addLayout(self.sideBarLayout)
        self.bodyLayout = QtWidgets.QGridLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.horizontalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.loginPage)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 801, 701))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.loginGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.loginGrid.setContentsMargins(0, 0, 0, 0)
        self.loginGrid.setSpacing(0)
        self.loginGrid.setObjectName("loginGrid")
        self.loginGrey6 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey6.setStyleSheet("border-radius: 0px;")
        self.loginGrey6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey6.setObjectName("loginGrey6")
        self.loginGrid.addWidget(self.loginGrey6, 2, 0, 1, 1)
        self.loginGrey4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey4.setStyleSheet("border-radius: 0px;")
        self.loginGrey4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey4.setObjectName("loginGrey4")
        self.loginGrid.addWidget(self.loginGrey4, 1, 0, 1, 1)
        self.loginWidget = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.loginWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.loginWidget.setObjectName("loginWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.loginWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 394, 498))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.loginVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.loginVLayout.setContentsMargins(0, 0, 0, 0)
        self.loginVLayout.setSpacing(0)
        self.loginVLayout.setObjectName("loginVLayout")
        self.loginLogo = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.loginLogo.setStyleSheet("padding-left: 120px;\n"
"padding-right: 120px;\n"
"margin-top: 60px;\n"
"")
        self.loginLogo.setText("")
        self.loginLogo.setIcon(icon)
        self.loginLogo.setIconSize(QtCore.QSize(140, 140))
        self.loginLogo.setObjectName("loginLogo")
        self.loginVLayout.addWidget(self.loginLogo)
        self.loginTitle = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(32)
        self.loginTitle.setFont(font)
        self.loginTitle.setStyleSheet("color: rgb(254, 140, 10);\n"
"padding-left: 120px;\n"
"padding-right: 120px;\n"
"padding-top: 5px;\n"
"padding-bottom: 40px;")
        self.loginTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.loginTitle.setObjectName("loginTitle")
        self.loginVLayout.addWidget(self.loginTitle)
        self.loginFormLayout = QtWidgets.QGridLayout()
        self.loginFormLayout.setObjectName("loginFormLayout")
        self.loginPassLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.loginPassLineEdit.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    margin: 5px;\n"
"    margin-right: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}")
        self.loginPassLineEdit.setInputMask("")
        self.loginPassLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPassLineEdit.setObjectName("loginPassLineEdit")
        self.loginFormLayout.addWidget(self.loginPassLineEdit, 1, 2, 1, 1)
        self.loginUserPic = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.loginUserPic.setStyleSheet("padding: 5px;\n"
"margin-left: 15px;")
        self.loginUserPic.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginUserPic.setIcon(icon2)
        self.loginUserPic.setIconSize(QtCore.QSize(25, 25))
        self.loginUserPic.setObjectName("loginUserPic")
        self.loginFormLayout.addWidget(self.loginUserPic, 0, 0, 1, 1)
        self.loginUserLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.loginUserLineEdit.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    margin: 5px;\n"
"    margin-right: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}")
        self.loginUserLineEdit.setObjectName("loginUserLineEdit")
        self.loginFormLayout.addWidget(self.loginUserLineEdit, 0, 2, 1, 1)
        self.loginPassPic = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.loginPassPic.setStyleSheet("padding: 5px;\n"
"margin-left: 15px;")
        self.loginPassPic.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginPassPic.setIcon(icon3)
        self.loginPassPic.setIconSize(QtCore.QSize(25, 25))
        self.loginPassPic.setObjectName("loginPassPic")
        self.loginFormLayout.addWidget(self.loginPassPic, 1, 0, 1, 1)
        self.loginVLayout.addLayout(self.loginFormLayout)
        self.loginButtonsHLayout = QtWidgets.QHBoxLayout()
        self.loginButtonsHLayout.setSpacing(0)
        self.loginButtonsHLayout.setObjectName("loginButtonsHLayout")
        self.registerBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.registerBtn.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 15px;\n"
"    margin: 20px;\n"
"    margin-bottom: 40px;\n"
"    margin-right: 5px;\n"
"    border-radius: 5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    border-style: solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.registerBtn.setObjectName("registerBtn")
        self.loginButtonsHLayout.addWidget(self.registerBtn)
        self.loginBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.loginBtn.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(28, 85, 255, 255), stop:1 rgba(94, 134, 255, 255));\n"
"    padding: 15px;\n"
"    margin: 20px;\n"
"    margin-bottom: 40px;\n"
"    margin-left: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(27, 82, 246, 255), stop:1 rgba(91, 130, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(32, 81, 227, 255), stop:1 rgba(71, 109, 224, 255));\n"
"}")
        self.loginBtn.setObjectName("loginBtn")
        self.loginButtonsHLayout.addWidget(self.loginBtn)
        self.loginVLayout.addLayout(self.loginButtonsHLayout)
        self.loginGrid.addWidget(self.loginWidget, 1, 1, 1, 1)
        self.loginGrey8 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey8.setStyleSheet("border-radius: 0px;")
        self.loginGrey8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey8.setObjectName("loginGrey8")
        self.loginGrid.addWidget(self.loginGrey8, 2, 2, 1, 1)
        self.loginGrey7 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey7.setStyleSheet("border-radius: 0px;")
        self.loginGrey7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey7.setObjectName("loginGrey7")
        self.loginGrid.addWidget(self.loginGrey7, 2, 1, 1, 1)
        self.loginGrey5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey5.setStyleSheet("border-radius: 0px;")
        self.loginGrey5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey5.setObjectName("loginGrey5")
        self.loginGrid.addWidget(self.loginGrey5, 1, 2, 1, 1)
        self.loginGrey3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey3.setStyleSheet("border-radius: 0px;")
        self.loginGrey3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey3.setObjectName("loginGrey3")
        self.loginGrid.addWidget(self.loginGrey3, 0, 2, 1, 1)
        self.loginGrey2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey2.setStyleSheet("border-radius: 0px;")
        self.loginGrey2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey2.setObjectName("loginGrey2")
        self.loginGrid.addWidget(self.loginGrey2, 0, 1, 1, 1)
        self.loginGrey1 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.loginGrey1.setStyleSheet("border-radius: 0px;")
        self.loginGrey1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginGrey1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginGrey1.setObjectName("loginGrey1")
        self.loginGrid.addWidget(self.loginGrey1, 0, 0, 1, 1)
        self.loginGrid.setColumnStretch(0, 100)
        self.loginGrid.setColumnStretch(1, 4)
        self.loginGrid.setColumnStretch(2, 100)
        self.loginGrid.setRowStretch(0, 100)
        self.loginGrid.setRowStretch(1, 5)
        self.loginGrid.setRowStretch(2, 100)
        self.stackedWidget.addWidget(self.loginPage)
        self.calendarioPage = QtWidgets.QWidget()
        self.calendarioPage.setObjectName("calendarioPage")
        self.gridLayoutWidget = QtWidgets.QWidget(self.calendarioPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.calendarioGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.calendarioGrid.setContentsMargins(0, 0, 0, 0)
        self.calendarioGrid.setObjectName("calendarioGrid")
        self.calendarioGrey3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey3.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey3.setObjectName("calendarioGrey3")
        self.calendarioGrid.addWidget(self.calendarioGrey3, 0, 2, 1, 1)
        self.calendarioGrey9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey9.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey9.setObjectName("calendarioGrey9")
        self.calendarioGrid.addWidget(self.calendarioGrey9, 3, 0, 1, 1)
        self.calendarioGrey1 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey1.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey1.setObjectName("calendarioGrey1")
        self.calendarioGrid.addWidget(self.calendarioGrey1, 0, 0, 1, 1)
        self.calendarioGrey6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey6.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey6.setObjectName("calendarioGrey6")
        self.calendarioGrid.addWidget(self.calendarioGrey6, 2, 0, 1, 1)
        self.calendarioGrey4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey4.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey4.setObjectName("calendarioGrey4")
        self.calendarioGrid.addWidget(self.calendarioGrey4, 1, 0, 1, 1)
        self.calendarioGrey2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey2.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey2.setObjectName("calendarioGrey2")
        self.calendarioGrid.addWidget(self.calendarioGrey2, 0, 1, 1, 1)
        self.calendarioGrey5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey5.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey5.setObjectName("calendarioGrey5")
        self.calendarioGrid.addWidget(self.calendarioGrey5, 1, 2, 1, 1)
        self.calendarioGrey11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey11.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey11.setObjectName("calendarioGrey11")
        self.calendarioGrid.addWidget(self.calendarioGrey11, 4, 0, 1, 1)
        self.calendarioGrey7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey7.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey7.setObjectName("calendarioGrey7")
        self.calendarioGrid.addWidget(self.calendarioGrey7, 2, 1, 1, 1)
        self.calendarioGrey8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey8.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey8.setObjectName("calendarioGrey8")
        self.calendarioGrid.addWidget(self.calendarioGrey8, 2, 2, 1, 1)
        self.calendarioGrey10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey10.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey10.setObjectName("calendarioGrey10")
        self.calendarioGrid.addWidget(self.calendarioGrey10, 3, 2, 1, 1)
        self.calendarioGrey12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey12.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey12.setObjectName("calendarioGrey12")
        self.calendarioGrid.addWidget(self.calendarioGrey12, 4, 1, 1, 1)
        self.calendarioGrey13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.calendarioGrey13.setStyleSheet("border-radius: 0px;")
        self.calendarioGrey13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarioGrey13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendarioGrey13.setObjectName("calendarioGrey13")
        self.calendarioGrid.addWidget(self.calendarioGrey13, 4, 2, 1, 1)
        self.calendarioMainWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.calendarioMainWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.calendarioMainWidget.setObjectName("calendarioMainWidget")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.calendarioMainWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 721, 591))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.calendarioMainGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.calendarioMainGridLayout.setContentsMargins(20, 20, 20, 20)
        self.calendarioMainGridLayout.setHorizontalSpacing(20)
        self.calendarioMainGridLayout.setObjectName("calendarioMainGridLayout")
        self.calendarioMainL3 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL3.setDragEnabled(True)
        self.calendarioMainL3.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL3.setWordWrap(True)
        self.calendarioMainL3.setObjectName("calendarioMainL3")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL3, 1, 2, 1, 1)
        self.calendarioMainD7 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD7.setFont(font)
        self.calendarioMainD7.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD7.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD7.setObjectName("calendarioMainD7")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD7, 2, 2, 1, 1)
        self.calendarioMainD1 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD1.setFont(font)
        self.calendarioMainD1.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD1.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD1.setObjectName("calendarioMainD1")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD1, 0, 0, 1, 1)
        self.calendarioMainD2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD2.setFont(font)
        self.calendarioMainD2.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD2.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD2.setObjectName("calendarioMainD2")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD2, 0, 1, 1, 1)
        self.calendarioMainD3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD3.setFont(font)
        self.calendarioMainD3.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD3.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD3.setObjectName("calendarioMainD3")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD3, 0, 2, 1, 1)
        self.calendarioMainD4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD4.setFont(font)
        self.calendarioMainD4.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD4.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD4.setObjectName("calendarioMainD4")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD4, 0, 3, 1, 1)
        self.calendarioMainL2 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL2.setMinimumSize(QtCore.QSize(102, 202))
        self.calendarioMainL2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL2.setDragEnabled(True)
        self.calendarioMainL2.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL2.setWordWrap(True)
        self.calendarioMainL2.setObjectName("calendarioMainL2")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL2, 1, 1, 1, 1)
        self.calendarioMainL4 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL4.setDragEnabled(True)
        self.calendarioMainL4.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL4.setWordWrap(True)
        self.calendarioMainL4.setObjectName("calendarioMainL4")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL4, 1, 3, 1, 1)
        self.calendarioMainD5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD5.setFont(font)
        self.calendarioMainD5.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD5.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD5.setObjectName("calendarioMainD5")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD5, 2, 0, 1, 1)
        self.calendarioMainL1 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL1.setMinimumSize(QtCore.QSize(102, 202))
        self.calendarioMainL1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL1.setDragEnabled(True)
        self.calendarioMainL1.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL1.setWordWrap(True)
        self.calendarioMainL1.setObjectName("calendarioMainL1")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL1, 1, 0, 1, 1)
        self.calendarioMainD6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioMainD6.setFont(font)
        self.calendarioMainD6.setStyleSheet("color: rgb(8, 21, 63);")
        self.calendarioMainD6.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD6.setObjectName("calendarioMainD6")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD6, 2, 1, 1, 1)
        self.calendarioMainD8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.calendarioMainD8.setFont(font)
        self.calendarioMainD8.setStyleSheet("color: rgb(151, 151, 151);")
        self.calendarioMainD8.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainD8.setObjectName("calendarioMainD8")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainD8, 2, 3, 1, 1)
        self.calendarioMainL5 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL5.setDragEnabled(True)
        self.calendarioMainL5.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL5.setWordWrap(True)
        self.calendarioMainL5.setObjectName("calendarioMainL5")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL5, 3, 0, 1, 1)
        self.calendarioMainL6 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL6.setDragEnabled(True)
        self.calendarioMainL6.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL6.setWordWrap(True)
        self.calendarioMainL6.setObjectName("calendarioMainL6")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL6, 3, 1, 1, 1)
        self.calendarioMainL7 = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.calendarioMainL7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 150;\n"
"min-height: 200;")
        self.calendarioMainL7.setDragEnabled(True)
        self.calendarioMainL7.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.calendarioMainL7.setWordWrap(True)
        self.calendarioMainL7.setObjectName("calendarioMainL7")
        self.calendarioMainGridLayout.addWidget(self.calendarioMainL7, 3, 2, 1, 1)
        self.calendarioMainVLayout = QtWidgets.QVBoxLayout()
        self.calendarioMainVLayout.setObjectName("calendarioMainVLayout")
        self.calendarioMainVaciarExpl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.calendarioMainVaciarExpl.setFont(font)
        self.calendarioMainVaciarExpl.setStyleSheet("color: rgb(151, 151, 151);\n"
"margin-top: 20px;\n"
"margin-bottom: 20px;")
        self.calendarioMainVaciarExpl.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarioMainVaciarExpl.setWordWrap(True)
        self.calendarioMainVaciarExpl.setObjectName("calendarioMainVaciarExpl")
        self.calendarioMainVLayout.addWidget(self.calendarioMainVaciarExpl)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.calendarioMainVLayout.addItem(spacerItem)
        self.calendarioMainVaciarLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.calendarioMainVaciarLabel.setStyleSheet("color: rgb(151, 151, 151);\n"
"margin-bottom: 10px;\n"
"margin-top: 10px;")
        self.calendarioMainVaciarLabel.setObjectName("calendarioMainVaciarLabel")
        self.calendarioMainVLayout.addWidget(self.calendarioMainVaciarLabel)
        self.calendarioMainCombo = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.calendarioMainCombo.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    padding: 5px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: rgb(207, 207, 207);\n"
"    selection-color: rgb(246, 246, 246);\n"
"}\n"
"\n"
"QComboBox::drop-down:focus {\n"
"    background-color: rgb(254, 140, 10);\n"
"    selection-color: rgb(246, 246, 246);\n"
"}")
        self.calendarioMainCombo.setObjectName("calendarioMainCombo")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainCombo.addItem("")
        self.calendarioMainVLayout.addWidget(self.calendarioMainCombo)
        self.calendarioMainVaciarBtn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.calendarioMainVaciarBtn.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(254, 140, 10, 255), stop:1 rgba(255, 190, 94, 255));\n"
"    padding: 6.5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(249, 137, 9, 255), stop:1 rgba(249, 186, 92, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(241, 133, 9, 255), stop:1 rgba(240, 179, 88, 255));\n"
"}")
        self.calendarioMainVaciarBtn.setObjectName("calendarioMainVaciarBtn")
        self.calendarioMainVLayout.addWidget(self.calendarioMainVaciarBtn)
        self.calendarioMainGridLayout.addLayout(self.calendarioMainVLayout, 3, 3, 1, 1)
        self.calendarioGrid.addWidget(self.calendarioMainWidget, 1, 1, 1, 1)
        self.calendarioAddWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.calendarioAddWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.calendarioAddWidget.setObjectName("calendarioAddWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.calendarioAddWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.calendarioAddVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.calendarioAddVLayout.setContentsMargins(0, 0, 0, 0)
        self.calendarioAddVLayout.setObjectName("calendarioAddVLayout")
        self.calendarioAddTitleHLayout = QtWidgets.QHBoxLayout()
        self.calendarioAddTitleHLayout.setObjectName("calendarioAddTitleHLayout")
        self.calendarioAddTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(16)
        self.calendarioAddTitle.setFont(font)
        self.calendarioAddTitle.setStyleSheet("color: rgb(8, 21, 63);\n"
"padding: 2px;\n"
"margin-left: 15px;\n"
"margin-top: 20px;")
        self.calendarioAddTitle.setObjectName("calendarioAddTitle")
        self.calendarioAddTitleHLayout.addWidget(self.calendarioAddTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.calendarioAddTitleHLayout.addItem(spacerItem1)
        self.calendarioAddBtn3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calendarioAddBtn3.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(254, 140, 10, 255), stop:1 rgba(255, 190, 94, 255));\n"
"    margin: 5px;\n"
"    margin-right: 20px;\n"
"    margin-top: 20px;\n"
"    padding: 6.5px;\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(249, 137, 9, 255), stop:1 rgba(249, 186, 92, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(241, 133, 9, 255), stop:1 rgba(240, 179, 88, 255));\n"
"}")
        self.calendarioAddBtn3.setObjectName("calendarioAddBtn3")
        self.calendarioAddTitleHLayout.addWidget(self.calendarioAddBtn3)
        self.calendarioAddVLayout.addLayout(self.calendarioAddTitleHLayout)
        self.calendarioAddForm = QtWidgets.QGridLayout()
        self.calendarioAddForm.setSpacing(0)
        self.calendarioAddForm.setObjectName("calendarioAddForm")
        self.calendarioAddLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.calendarioAddLabel0.setStyleSheet("color: rgb(151, 151, 151);\n"
"padding: 2px;\n"
"padding-bottom: 0px;\n"
"margin-left: 15px;")
        self.calendarioAddLabel0.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.calendarioAddLabel0.setObjectName("calendarioAddLabel0")
        self.calendarioAddForm.addWidget(self.calendarioAddLabel0, 3, 0, 1, 1)
        self.calendarioAddCombo1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.calendarioAddCombo1.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    margin: 5px;\n"
"    margin-bottom: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: rgb(207, 207, 207);\n"
"    selection-color: rgb(246, 246, 246);\n"
"}\n"
"\n"
"QComboBox::drop-down:focus {\n"
"    background-color: rgb(254, 140, 10);\n"
"    selection-color: rgb(246, 246, 246);\n"
"}")
        self.calendarioAddCombo1.setObjectName("calendarioAddCombo1")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddCombo1.addItem("")
        self.calendarioAddForm.addWidget(self.calendarioAddCombo1, 4, 1, 1, 1)
        self.calendarioAddLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.calendarioAddLabel1.setStyleSheet("color: rgb(151, 151, 151);\n"
"padding: 2px;\n"
"padding-bottom: 0px;")
        self.calendarioAddLabel1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.calendarioAddLabel1.setObjectName("calendarioAddLabel1")
        self.calendarioAddForm.addWidget(self.calendarioAddLabel1, 3, 1, 1, 1)
        self.calendarioAddLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.calendarioAddLabel2.setStyleSheet("color: rgb(151, 151, 151);\n"
"padding: 2px;\n"
"padding-bottom: 0px;")
        self.calendarioAddLabel2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.calendarioAddLabel2.setObjectName("calendarioAddLabel2")
        self.calendarioAddForm.addWidget(self.calendarioAddLabel2, 3, 2, 1, 1)
        self.calendarioAddCombo2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.calendarioAddCombo2.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    margin: 5px;\n"
"    margin-bottom: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: rgb(207, 207, 207);\n"
"    selection-color: rgb(246, 246, 246);\n"
"}\n"
"\n"
"QComboBox::drop-down:focus {\n"
"    background-color: rgb(254, 140, 10);\n"
"    selection-color: rgb(246, 246, 246);\n"
"}")
        self.calendarioAddCombo2.setObjectName("calendarioAddCombo2")
        self.calendarioAddForm.addWidget(self.calendarioAddCombo2, 4, 2, 1, 1)
        self.calendarioAddLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.calendarioAddLineEdit.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    margin: 5px;\n"
"    margin-bottom: 20px;\n"
"    margin-left: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}")
        self.calendarioAddLineEdit.setObjectName("calendarioAddLineEdit")
        self.calendarioAddForm.addWidget(self.calendarioAddLineEdit, 4, 0, 1, 1)
        self.calendarioAddBtn1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calendarioAddBtn1.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(28, 85, 255, 255), stop:1 rgba(94, 134, 255, 255));\n"
"    margin: 5px;\n"
"    margin-bottom: 20px;\n"
"    margin-right: 20px;\n"
"    padding: 6.5px;\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(27, 82, 246, 255), stop:1 rgba(91, 130, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(32, 81, 227, 255), stop:1 rgba(71, 109, 224, 255));\n"
"}")
        self.calendarioAddBtn1.setObjectName("calendarioAddBtn1")
        self.calendarioAddForm.addWidget(self.calendarioAddBtn1, 4, 3, 1, 1)
        self.calendarioAddBtn2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calendarioAddBtn2.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(28, 85, 255, 255), stop:1 rgba(94, 134, 255, 255));\n"
"    margin: 4px;\n"
"    margin-right: 19px;\n"
"    margin-bottom: 0px;\n"
"    padding: 6.5px;\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(27, 82, 246, 255), stop:1 rgba(91, 130, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(32, 81, 227, 255), stop:1 rgba(71, 109, 224, 255));\n"
"}")
        self.calendarioAddBtn2.setObjectName("calendarioAddBtn2")
        self.calendarioAddForm.addWidget(self.calendarioAddBtn2, 3, 3, 1, 1)
        self.calendarioAddForm.setColumnStretch(0, 5)
        self.calendarioAddForm.setColumnStretch(2, 3)
        self.calendarioAddVLayout.addLayout(self.calendarioAddForm)
        self.calendarioGrid.addWidget(self.calendarioAddWidget, 3, 1, 1, 1)
        self.calendarioGrid.setColumnStretch(0, 1)
        self.calendarioGrid.setColumnStretch(1, 30)
        self.calendarioGrid.setColumnStretch(2, 1)
        self.calendarioGrid.setRowStretch(0, 2)
        self.calendarioGrid.setRowStretch(4, 2)
        self.stackedWidget.addWidget(self.calendarioPage)
        self.busquedaPage = QtWidgets.QWidget()
        self.busquedaPage.setObjectName("busquedaPage")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.busquedaPage)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 801, 701))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.busquedaGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.busquedaGrid.setContentsMargins(0, 0, 0, 0)
        self.busquedaGrid.setObjectName("busquedaGrid")
        self.busquedaGrey1 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey1.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey1.setObjectName("busquedaGrey1")
        self.busquedaGrid.addWidget(self.busquedaGrey1, 0, 0, 1, 1)
        self.busquedaGrey8 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey8.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey8.setObjectName("busquedaGrey8")
        self.busquedaGrid.addWidget(self.busquedaGrey8, 2, 2, 1, 1)
        self.busquedaGrey9 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey9.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey9.setObjectName("busquedaGrey9")
        self.busquedaGrid.addWidget(self.busquedaGrey9, 3, 0, 1, 1)
        self.busquedaGrey4 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey4.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey4.setObjectName("busquedaGrey4")
        self.busquedaGrid.addWidget(self.busquedaGrey4, 1, 0, 1, 1)
        self.busquedaGrey6 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey6.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey6.setObjectName("busquedaGrey6")
        self.busquedaGrid.addWidget(self.busquedaGrey6, 2, 0, 1, 1)
        self.busquedaGrey2 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey2.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey2.setObjectName("busquedaGrey2")
        self.busquedaGrid.addWidget(self.busquedaGrey2, 0, 1, 1, 1)
        self.busquedaGrey5 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey5.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey5.setObjectName("busquedaGrey5")
        self.busquedaGrid.addWidget(self.busquedaGrey5, 1, 2, 1, 1)
        self.busquedaGrey3 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey3.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey3.setObjectName("busquedaGrey3")
        self.busquedaGrid.addWidget(self.busquedaGrey3, 0, 2, 1, 1)
        self.busquedaGrey7 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey7.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey7.setObjectName("busquedaGrey7")
        self.busquedaGrid.addWidget(self.busquedaGrey7, 2, 1, 1, 1)
        self.busquedaGrey11 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey11.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey11.setObjectName("busquedaGrey11")
        self.busquedaGrid.addWidget(self.busquedaGrey11, 4, 0, 1, 1)
        self.busquedaGrey12 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey12.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey12.setObjectName("busquedaGrey12")
        self.busquedaGrid.addWidget(self.busquedaGrey12, 4, 1, 1, 1)
        self.busquedaGrey13 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey13.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey13.setObjectName("busquedaGrey13")
        self.busquedaGrid.addWidget(self.busquedaGrey13, 4, 2, 1, 1)
        self.busquedaSearchWidget = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.busquedaSearchWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.busquedaSearchWidget.setObjectName("busquedaSearchWidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.busquedaSearchWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 741, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.busquedaSearchHLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.busquedaSearchHLayout.setContentsMargins(20, 20, 20, 20)
        self.busquedaSearchHLayout.setObjectName("busquedaSearchHLayout")
        self.busquedaSearchLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.busquedaSearchLineEdit.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(207, 207, 207);\n"
"    background-color: rgb(246, 246, 246);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(254, 140, 10);\n"
"    border-width: 2px;\n"
"}")
        self.busquedaSearchLineEdit.setObjectName("busquedaSearchLineEdit")
        self.busquedaSearchHLayout.addWidget(self.busquedaSearchLineEdit)
        self.busquedaSearchBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.busquedaSearchBtn.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(28, 85, 255, 255), stop:1 rgba(94, 134, 255, 255));\n"
"    padding: 6.5px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(27, 82, 246, 255), stop:1 rgba(91, 130, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(32, 81, 227, 255), stop:1 rgba(71, 109, 224, 255));\n"
"}")
        self.busquedaSearchBtn.setObjectName("busquedaSearchBtn")
        self.busquedaSearchHLayout.addWidget(self.busquedaSearchBtn)
        self.busquedaGrid.addWidget(self.busquedaSearchWidget, 1, 1, 1, 1)
        self.busquedaResultsWidget = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.busquedaResultsWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.busquedaResultsWidget.setObjectName("busquedaResultsWidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.busquedaResultsWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 741, 561))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.busquedaResultsVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.busquedaResultsVLayout.setContentsMargins(20, 20, 20, 20)
        self.busquedaResultsVLayout.setObjectName("busquedaResultsVLayout")
        self.busquedaResultsList = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.busquedaResultsList.setMinimumSize(QtCore.QSize(502, 402))
        self.busquedaResultsList.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 246, 246);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(8, 21, 63);\n"
"min-width: 500;\n"
"min-height: 400;")
        self.busquedaResultsList.setWordWrap(True)
        self.busquedaResultsList.setObjectName("busquedaResultsList")
        self.busquedaResultsVLayout.addWidget(self.busquedaResultsList)
        self.busquedaResultsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.busquedaResultsBtn.setStyleSheet("QPushButton {\n"
"    border-width: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(28, 85, 255, 255), stop:1 rgba(94, 134, 255, 255));\n"
"    padding: 6.5px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(27, 82, 246, 255), stop:1 rgba(91, 130, 248, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(32, 81, 227, 255), stop:1 rgba(71, 109, 224, 255));\n"
"}")
        self.busquedaResultsBtn.setObjectName("busquedaResultsBtn")
        self.busquedaResultsVLayout.addWidget(self.busquedaResultsBtn)
        self.busquedaGrid.addWidget(self.busquedaResultsWidget, 3, 1, 1, 1)
        self.busquedaGrey10 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.busquedaGrey10.setStyleSheet("border-radius: 0px;")
        self.busquedaGrey10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.busquedaGrey10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.busquedaGrey10.setObjectName("busquedaGrey10")
        self.busquedaGrid.addWidget(self.busquedaGrey10, 3, 2, 1, 1)
        self.busquedaGrid.setColumnStretch(0, 1)
        self.busquedaGrid.setColumnStretch(1, 30)
        self.busquedaGrid.setColumnStretch(2, 1)
        self.busquedaGrid.setRowStretch(0, 2)
        self.busquedaGrid.setRowStretch(1, 2)
        self.busquedaGrid.setRowStretch(3, 30)
        self.busquedaGrid.setRowStretch(4, 2)
        self.stackedWidget.addWidget(self.busquedaPage)
        self.bodyLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.mainLayout.addLayout(self.bodyLayout)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 100)
        MainWindow.setCentralWidget(self.centralwidget)



        # General scaling
        mainLayoutWidget = QWidget()
        mainLayoutWidget.setLayout(self.mainLayout)
        MainWindow.setCentralWidget(mainLayoutWidget)

        # Login page scaling
        self.loginPage.setLayout(self.loginGrid)

        # Login widget scaling
        self.loginWidget.setLayout(self.loginVLayout)

        # Calendario page scaling
        self.calendarioPage.setLayout(self.calendarioGrid)

        # Calendario main widget scaling
        self.calendarioMainWidget.setLayout(self.calendarioMainGridLayout)

        # Calendario add widget scaling
        self.calendarioAddWidget.setLayout(self.calendarioAddVLayout)

        # Busqueda page scaling
        self.busquedaPage.setLayout(self.busquedaGrid)

        # Busqueda search widget scaling
        self.busquedaSearchWidget.setLayout(self.busquedaSearchHLayout)

        # Busqueda results widget scaling
        self.busquedaResultsWidget.setLayout(self.busquedaResultsVLayout)
        
        # NOTE(Erton): Try float (left, right), min-width, max-width...



        # Connections
        self.btnCalendario.clicked.connect(lambda: self.changePage(1))
        self.btnBusqueda.clicked.connect(lambda: self.changePage(2))



        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def changePage(self, index):
        self.stackedWidget.setCurrentIndex(index)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.banner.setText(_translate("MainWindow", " BoxPile"))
        self.btnCalendario.setText(_translate("MainWindow", "Calendario"))
        self.btnSeguimiento.setText(_translate("MainWindow", "Seguimiento"))
        self.btnBusqueda.setText(_translate("MainWindow", "Búsqueda"))
        self.btnUser.setText(_translate("MainWindow", "  @username\n"
"  0 Amigos"))
        self.loginTitle.setText(_translate("MainWindow", "BoxPile"))
        self.loginPassLineEdit.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.loginUserLineEdit.setPlaceholderText(_translate("MainWindow", "Nombre de usuario"))
        self.registerBtn.setText(_translate("MainWindow", "Crear cuenta"))
        self.loginBtn.setText(_translate("MainWindow", "PushButton"))
        self.calendarioMainD7.setText(_translate("MainWindow", "Domingo"))
        self.calendarioMainD1.setText(_translate("MainWindow", "Lunes"))
        self.calendarioMainD2.setText(_translate("MainWindow", "Martes"))
        self.calendarioMainD3.setText(_translate("MainWindow", "Miércoles"))
        self.calendarioMainD4.setText(_translate("MainWindow", "Jueves"))
        self.calendarioMainD5.setText(_translate("MainWindow", "Viernes"))
        self.calendarioMainD6.setText(_translate("MainWindow", "Sábado"))
        self.calendarioMainD8.setText(_translate("MainWindow", "Vaciar"))
        self.calendarioMainVaciarExpl.setText(_translate("MainWindow", "Vacía los eventos marcados de un día para reorganizarlo."))
        self.calendarioMainVaciarLabel.setText(_translate("MainWindow", "Día"))
        self.calendarioMainCombo.setItemText(0, _translate("MainWindow", "Lunes"))
        self.calendarioMainCombo.setItemText(1, _translate("MainWindow", "Martes"))
        self.calendarioMainCombo.setItemText(2, _translate("MainWindow", "Miércoles"))
        self.calendarioMainCombo.setItemText(3, _translate("MainWindow", "Jueves"))
        self.calendarioMainCombo.setItemText(4, _translate("MainWindow", "Viernes"))
        self.calendarioMainCombo.setItemText(5, _translate("MainWindow", "Sábado"))
        self.calendarioMainCombo.setItemText(6, _translate("MainWindow", "Domingo"))
        self.calendarioMainVaciarBtn.setText(_translate("MainWindow", "Vacia el día"))
        self.calendarioAddTitle.setText(_translate("MainWindow", "Crea un nuevo evento"))
        self.calendarioAddBtn3.setText(_translate("MainWindow", "Reinicia el evento"))
        self.calendarioAddLabel0.setText(_translate("MainWindow", "Nombre del evento"))
        self.calendarioAddCombo1.setItemText(0, _translate("MainWindow", "Lunes"))
        self.calendarioAddCombo1.setItemText(1, _translate("MainWindow", "Martes"))
        self.calendarioAddCombo1.setItemText(2, _translate("MainWindow", "Miércoles"))
        self.calendarioAddCombo1.setItemText(3, _translate("MainWindow", "Jueves"))
        self.calendarioAddCombo1.setItemText(4, _translate("MainWindow", "Viernes"))
        self.calendarioAddCombo1.setItemText(5, _translate("MainWindow", "Sábado"))
        self.calendarioAddCombo1.setItemText(6, _translate("MainWindow", "Domingo"))
        self.calendarioAddLabel1.setText(_translate("MainWindow", "Día"))
        self.calendarioAddLabel2.setText(_translate("MainWindow", "Compartir (opcional)"))
        self.calendarioAddBtn1.setText(_translate("MainWindow", "Crea"))
        self.calendarioAddBtn2.setText(_translate("MainWindow", "+"))
        self.busquedaSearchBtn.setText(_translate("MainWindow", "Busca"))
        self.busquedaResultsBtn.setText(_translate("MainWindow", "Visitar usuario seleccionado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
