# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boxpile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# NOTE(Erton): Definitive version of sidebar

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setStyleSheet("color: rgb(246, 246, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1081, 721))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.sideBarLayout = QtWidgets.QVBoxLayout()
        self.sideBarLayout.setSpacing(0)
        self.sideBarLayout.setObjectName("sideBarLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(254, 140, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"padding: 50px;\n"
"padding-left: 40px;\n"
"text-align: left;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/logoTR_orange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_2.setObjectName("pushButton_2")
        self.sideBarLayout.addWidget(self.pushButton_2)
        self.btnCalendario = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalendario.setFont(font)
        self.btnCalendario.setStyleSheet("QPushButton {\n"
"    padding: 20px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"")
        self.btnCalendario.setObjectName("btnCalendario")
        self.sideBarLayout.addWidget(self.btnCalendario)
        self.btnSeguimiento = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSeguimiento.setFont(font)
        self.btnSeguimiento.setStyleSheet("QPushButton {\n"
"    padding: 20px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"")
        self.btnSeguimiento.setObjectName("btnSeguimiento")
        self.sideBarLayout.addWidget(self.btnSeguimiento)
        self.btnBusqueda = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnBusqueda.setFont(font)
        self.btnBusqueda.setStyleSheet("QPushButton {\n"
"    padding: 20px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"")
        self.btnBusqueda.setObjectName("btnBusqueda")
        self.sideBarLayout.addWidget(self.btnBusqueda)
        self.sideBarFill = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.sideBarFill.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.sideBarFill.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBarFill.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBarFill.setObjectName("sideBarFill")
        self.sideBarLayout.addWidget(self.sideBarFill)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(8, 21, 63);\n"
"padding: 20px;\n"
"padding-left: 40px;\n"
"text-align: left")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/logoTR_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(45, 45))
        self.pushButton.setObjectName("pushButton")
        self.sideBarLayout.addWidget(self.pushButton)
        self.mainLayout.addLayout(self.sideBarLayout)
        self.bodyLayout = QtWidgets.QVBoxLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bodyLayout.addWidget(self.label)
        self.mainLayout.addLayout(self.bodyLayout)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 100)
        MainWindow.setCentralWidget(self.centralwidget)

        mainLayoutWidget = QWidget()
        mainLayoutWidget.setLayout(self.mainLayout)
        MainWindow.setCentralWidget(mainLayoutWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", " BoxPile"))
        self.btnCalendario.setText(_translate("MainWindow", "Calendario"))
        self.btnSeguimiento.setText(_translate("MainWindow", "Calendario"))
        self.btnBusqueda.setText(_translate("MainWindow", "Calendario"))
        self.pushButton.setText(_translate("MainWindow", "  @username\n"
"  0 Amigos"))
        self.label.setText(_translate("MainWindow", "Body"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
