# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boxpile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setStyleSheet("color: rgb(246, 246, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1071, 721))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.sideBar_frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.sideBar_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.sideBar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar_frame.setObjectName("sideBar_frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.sideBar_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 271, 701))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sideBar_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        
        # NOTE(Erton): Added this
        self.sideBar_layout.setGeometry(QtCore.QRect(0, 0, self.sideBar_frame.width(), self.sideBar_frame.height()))
        # SEEMS TO WORK, BUT IT IS NOT DYNAMIC

        self.sideBar_layout.setContentsMargins(0, 0, 0, 0)
        self.sideBar_layout.setObjectName("sideBar_layout")
        self.btnCalendario = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalendario.setFont(font)
        self.btnCalendario.setStyleSheet("QPushButton {\n"
"    padding: 15px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"")
        self.btnCalendario.setObjectName("btnCalendario")
        self.sideBar_layout.addWidget(self.btnCalendario)
        self.btnSeguimientol = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSeguimientol.setFont(font)
        self.btnSeguimientol.setStyleSheet("QPushButton {\n"
"    padding: 15px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"")
        self.btnSeguimientol.setObjectName("btnSeguimientol")
        self.sideBar_layout.addWidget(self.btnSeguimientol)
        self.btnBusqueda = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnBusqueda.setFont(font)
        self.btnBusqueda.setStyleSheet("QPushButton {\n"
"    padding: 15px;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"    color: rgb(8, 21, 63);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(246, 246, 246)\n"
"}\n"
"")
        self.btnBusqueda.setObjectName("btnBusqueda")
        self.sideBar_layout.addWidget(self.btnBusqueda)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sideBar_layout.addItem(spacerItem)
        self.mainLayout.addWidget(self.sideBar_frame)
        self.bodyLayout = QtWidgets.QVBoxLayout()
        self.bodyLayout.setObjectName("bodyLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bodyLayout.addWidget(self.label)
        self.mainLayout.addLayout(self.bodyLayout)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 3)

        # Centralize layout NOTE(Erton): Works, create a custom widget and then set its layout to the desired one, then center the widget in MainWindow
        mainLayoutWidget = QWidget()
        mainLayoutWidget.setLayout(self.mainLayout)
        MainWindow.setCentralWidget(mainLayoutWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # asign layout to window dimensions
        # self.mainLayout.setCentralWidget()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCalendario.setText(_translate("MainWindow", "Calendario"))
        self.btnSeguimientol.setText(_translate("MainWindow", "Seguimiento"))
        self.btnBusqueda.setText(_translate("MainWindow", "Búsqueda"))
        self.label.setText(_translate("MainWindow", "Body"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
